root: true
extends: airbnb
globals:
  __DEV__: true
parser: babel-eslint
rules:
  react/jsx-quotes: 0
  jsx-quotes:
    - 2
    - prefer-double
  brace-style:
    - 2
    - stroustrup
    - allowSingleLine: true
  indent:
    - 2
    - 2
    - SwitchCase: 1
  id-length:
    - 2
    - min: 1
  new-cap: 0
  max-len:
    - 2
    - 120
  no-use-before-define:
    - 2
    - nofunc
  spaced-comment:
    - 0
